version: '3.1'

services:
  pgdb:
    image: pg-fibo
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  fibo:
    image: fibo
    ports: 
      - "8081:8081"
    depends_on: 
      - "pgdb"
    environment:
      - PGHOST=pgdb
  